- name: get vault credentials
  hosts: localhost
  connection: local
  tasks:
    - name: Print password
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'secret=/v1/test/data/My_credentials token={{ vault_token }} url=http://:172.31.94.86:8200') }}"